src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\DTO\CustomerDTO;
use App\DTO\TicketDTO;
use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TicketRepository")
 */
class Ticket
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(name="id", type="integer")
     */
    private ?int $id;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer")
     * @ORM\JoinColumn(name="customer", referencedColumnName="id", nullable=false)
     */
    private Customer $customer;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Flight")
     * @ORM\JoinColumn(name="flight", referencedColumnName="id", nullable=false)
     */
    private Flight $flight;
    /**
     * @ORM\Column(name="flight_date", type="datetime", nullable=false)
     */
    private DateTime $flight_date;
    /**
     * @ORM\Column(name="status", type="string", length=100, options={"default" : "забронирован"})
     */
    private string $status = 'Забронирован';

    /**
     * @ORM\Column(type="integer")
     */
    private $price;


    public function __construct(Customer $customer, Flight $flight, DateTime $flight_date)
    {
        $this->customer = $customer;
        $this->flight = $flight;
        $this->flight_date = $flight_date;
    }

    public static function createFromDto(TicketDTO $dto): self
    {
        return new self($dto->getCustomer(), $dto->getFlight(), $dto->getFlightDate());
    }

    public function getCustomer(): Customer
    {
        return $this->customer;
    }

    public function setCustomer(Customer $customer): void
    {
        $this->customer = $customer;
    }

    public function getFlight(): Flight
    {
        return $this->flight;
    }

    public function setFlight(Flight $flight): void
    {
        $this->flight = $flight;
    }

    public function getFlightDate(): DateTime
    {
        return $this->flight_date;
    }

    public function setFlightDate(DateTime $flight_date): void
    {
        $this->flight_date = $flight_date;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $Price): self
    {
        $this->price = $Price;

        return $this;
    }


}

templates/app/addCustomer.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% block title %}Добавление пассажира{% endblock %}
{% block body %}

    {{ form_start(form) }}
    <h1 class="text-centre">Пассажир</h1>
    <div class="row g-3 align-item-center">
        <div class="col">
            {{ form_row(form.f) }}
        </div>
        <div class="col">
            {{ form_row(form.i) }}
        </div>
        <div class="col">
            {{ form_row(form.o) }}
        </div>
        <div class="col">
            <p class="vertical-align">
                Пасспорт
            </p>
        </div>
        <div class="col">
            {{ form_row(form.ps) }}
        </div>
        <div class="col">
            {{ form_row(form.pn) }}
        </div>
    </div>
    <div class="row g-3 text-centre">
        <div class="col">
            {{ form_row(form.save) }}
        </div>
    </div>



    {{ form_end(form) }}


    <style>
        #add_customer_save {
            width: 250px;
        }
    </style>


{% endblock %}

templates/app/bookTicket.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{% block title %}Бронирование билета{% endblock %}
{% block body %}
    {{ form_start(form) }}
    <h1 class="text-centre">Бронирование билета</h1>
    <div class="row g-3 align-item-center">
        <div class="col-md-6">
            {{ form_row(form.flight) }}
        </div>
        <div class="col-md-2">
            {{ form_row(form.flightDate) }}
        </div>
    </div>
    <div class="row g-3 align-item-center">
        <div class="col-md-6">
            {{ form_row(form.customer) }}
        </div>
    </div>
    <div>
        <a href="{{ path('app.addCustomer') }}">Добавить нового пассажира в систему +</a>
    </div>
    <div class="row g-3 text-centre">
        <div class="col">
            {{ form_row(form.save) }}
        </div>
    </div>


    {{ form_end(form) }}

    <style>
        #book_ticket_save {
            width: 250px;
        }
    </style>

{% endblock %}